### ISSUE TITLE
Warning on python3.8-dev

### ISSUE THREAD

**Issue by fansgit** [deadsnakes/issues#106]
Tried to install `python3.8-dev` on `16.04`:

```
WARNING: non-empty directory on upgrade: /usr/include/python3.8
total 692
-rw-r--r-- 1 root root 26491 Dec 22 08:15 Python-ast.h
...
-rw-r--r-- 1 root root  2866 Dec 22 08:15 weakrefobject.h
```

**Comment by asottile** [comment]
I've noticed this warning as well, though as far as I can tell it's harmless 🤷‍♂ 

The upstream packages are built in the same way

**Comment by asottile** [comment]
looks like upstream just deletes that file:

```console
$ diff -u <(ls debian/*postinst* | cut -d/ -f2 | sort) <(ls ../python3.8/debian/*postinst* | cut -d/ -f4 | sort)
--- /dev/fd/63	2019-12-31 09:34:58.891789616 -0800
+++ /dev/fd/62	2019-12-31 09:34:58.891789616 -0800
@@ -2,6 +2,7 @@
 libPVER-minimal.postinst.in
 libPVER-testsuite.postinst.in
 PVER-dbg.postinst.in
+PVER-dev.postinst.in
 PVER-minimal.postinst.in
 PVER.postinst.in
 PVER-venv.postinst.in
```

I guess the package has drifted since it was exported, I can pull in that change

**Comment by asottile** [comment]
seems to only be an issue for python3.8+, which makes sense -- this is part of the `python3.8m` -> `python3.8` transition

**Comment by asottile** [comment]
This has been fixed in:

- [python3.8](https://github.com/deadsnakes/python3.8) (should be available in <30 minutes)
- [python3.9](https://github.com/deadsnakes/python3.9) (should be available in <30 minutes)
- [python3.8-nightly](https://github.com/deadsnakes/python3.8-nightly) (should be available within 24 hours (when the nightly job kicks))
- [python3.9-nightly](https://github.com/deadsnakes/python3.9-nightly) (should be available within 24 hours (when the nightly job kicks))
- [python3.10](https://github.com/asottile/python3.10) (should be available in <30 minutes)

**Comment by asottile** [comment]
thanks again for the issue! 🎉

**Comment by fansgit** [comment]
Happy new year :tada: Thanks for the instant fix and the spirit of striving for perfection :+1:
