### ISSUE TITLE
how to rebuild packages with sync default modules installed in each python version?

### ISSUE THREAD

**Issue by mckaygerhard** [deadsnakes/issues#113]
### description

@asottile  why the ppa said "this will not work with default python pacakges modules"? what does that means, in this scenario:

1) i have python 2.7 with packages modules but are by example 2.7.1
2) i want to install python 2.7 from ppa due we have there 2.7.99
3) will this packaged version 2.7.99 will work with the prevoulsy modules ?

**if not due some path or setting was changed how can i re-build that packages with corrrect default settings?**

### os information

Debian

#### lsb_release -a

dont make sense here in this issue, but any version of debian

#### uname -a

each default kernel in each target debian

**Comment by asottile** [comment]
we don't support overwriting the primary python that ships with the distribution (for example on ubuntu:bionic that would be python3.6 + python2.7).  The reason for this is there are thousands of packages built against the version shipped with the distribution and a specific expectation of how those packages are built (which we sometimes/often deviate from intentionally/accidentally)

as such, we don't support that and you're on your own to attempt such a thing (**it might work, it might not**, but it's not easy).  If you're looking for upgraded versions of the default python I'd suggest upgrading distributions instead of trying to build a franken-debian ;)

**Comment by mckaygerhard** [comment]
update distribution are not a smart way when the kernel removed modules for specific hardware that still works as spected and better than other! .. umm ok .. 

but what do you changed in that specific case of bionic by example? @asottile ?

**Comment by asottile** [comment]
I'm sorry I don't understand your last comment
