### ISSUE TITLE
[action] deadsnakes action uses deprecated ::add-path::

### ISSUE THREAD

**Issue by asottile** [deadsnakes/issues#135]
https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files

https://github.com/deadsnakes/action/blob/dafca658ce5a39e29d3f1d1da2d9a343c1f9ce9e/bin/install-python#L84

**Comment by webknjaz** [comment]
This is now more urgent because the old way has finally stopped working. Example: https://github.com/pypa/setuptools/pull/2457/checks?check_run_id=1418912282#step:3:13.

> Error: Unable to process command '::set-env name=PYTHON_VERSION::3.8-dev' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
Error: Unable to process command '::set-env name=USE_DEADSNAKES::true' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
Set up Python ${{ env.PYTHON_VERSION }} (deadsnakes)

**Comment by webknjaz** [comment]
Workaround example: https://github.com/sphinx-doc/sphinx/pull/8440/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R49-R50.

**Comment by asottile** [comment]
if someone wants to fix this the patch is relatively straightforward in the file listed in the original issue -- essentially `echo '::set-env foo=bar'` needs to be replaced with `echo 'foo=bar' >> $GITHUB_ENV`

**Comment by asottile** [comment]
v2.0.1 has a fix for this: https://github.com/deadsnakes/action/releases/tag/v2.0.1
