### ISSUE TITLE
focal, python3.9, align with upstream on files included

### ISSUE THREAD

**Issue by asottile** [deadsnakes/issues#148]
### description

currently `typing.py` is in a different package than upstream which causes conflicts when upgrading / downgrading

```
Unpacking libpython3.9-stdlib:amd64 (3.9.1-1+focal1) over (3.9.0-5~20.04) ...
dpkg: error processing archive /tmp/apt-dpkg-install-yeGUg5/5-libpython3.9-stdlib_3.9.1-1+focal1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/typing.py', which is also in package libpython3.9-minimal:amd64 3.9.0-5~20.04
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

```

#### uname -a

```
$ uname -a
Linux babibox 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
The usual fix is `sudo apt install -yf` which will resolve the conflict

**Comment by JimmyPnote** [comment]
Yeah

**Comment by PaluMacil** [comment]
This might not be useful for solving this in deadsnakes (if that's even where the problem lies), but for someone who was confused and wound up in a bad spot, here is my full fix to work around this:

I ran into this same issue today. Someone recommended I run `sudo apt-get -f install` like the person above. When I opened Pycharm, my virtualenv was broken and I'm not really what sort of state I got myself into. I had originally made the virtualenv automatically through Pycharm's Poetry extension, and I'm wondering if Poetry removed it when it detected something wrong. This update did seem to move the patch version of Python up from 3.9.5 to 3.9.6. Regardless, I deleted the environment entry from `~/.cache/pypoetry/virtualenvs/envs.toml` as the folder already seemed to be gone, reopened PyCharm, and then selected to create an interpreter with Poetry (the poetry extension is required). The project seems perfectly operational again.

**Comment by asottile** [comment]
this should be fixed now, however there will be one round of `-yf` still needed to get to this alignment

**Comment by MrCreosote** [comment]
Let me know if I should make a new ticket, or if this isn't the appropriate place, but I just tried to install `python3.9-dev an hour or so ago and it broke in the same way as above, and at this point `apt install` seems to be generally broken. When I try the workaround above:

```shell
$ sudo apt install -yf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libpython3.9-minimal libpython3.9-stdlib
The following packages will be upgraded:
  libpython3.9-minimal libpython3.9-stdlib
2 upgraded, 0 newly installed, 0 to remove and 334 not upgraded.
6 not fully installed or removed.
Need to get 0 B/2,485 kB of archives.
After this operation, 72.7 kB of additional disk space will be used.
(Reading database ... 184205 files and directories currently installed.)
Preparing to unpack .../libpython3.9-stdlib_3.9.13-1+bionic1_amd64.deb ...
Unpacking libpython3.9-stdlib:amd64 (3.9.13-1+bionic1) over (3.9.6-1+bionic1) ...
dpkg: error processing archive /var/cache/apt/archives/libpython3.9-stdlib_3.9.13-1+bionic1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/_sysconfigdata__linux_x86_64-linux-gnu.py', which is also in package libpython3.9-minimal:amd64 3.9.6-1+bionic1
Preparing to unpack .../libpython3.9-minimal_3.9.13-1+bionic1_amd64.deb ...
Unpacking libpython3.9-minimal:amd64 (3.9.13-1+bionic1) over (3.9.6-1+bionic1) ...
dpkg: error processing archive /var/cache/apt/archives/libpython3.9-minimal_3.9.13-1+bionic1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/python3.9/typing.py', which is also in package libpython3.9-stdlib:amd64 3.9.6-1+bionic1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libpython3.9-stdlib_3.9.13-1+bionic1_amd64.deb
 /var/cache/apt/archives/libpython3.9-minimal_3.9.13-1+bionic1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by asottile** [comment]
> Unpacking libpython3.9-minimal:amd64 (3.9.13-1+bionic1) over (3.9.6-1+bionic1) ...

wow, you haven't updated in nearly a year ?

**Comment by MrCreosote** [comment]
For posterity, what worked for me was purging python3.9 completely as per [this answer](https://askubuntu.com/a/1415030/195905), then apt update / upgrade / install.
