### ISSUE TITLE
Can't perform apt update for artful

### ISSUE THREAD

**Issue by Pehat** [deadsnakes/issues#59]
### description
I get the error below:
```
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Is artful release supported?
### os information
MATE Linux
#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

#### uname -a

```
Linux renat-ubuntu 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
deadsnakes currently only supports lts releases.

You have a couple options on non-lts releases:
- build from source (either using [this](https://github.com/deadsnakes/docs/wiki/Building-Deadsnakes-Packages-from-Git) or the builder scripts provided in [runbooks](https://github.com/deadsnakes/runbooks)
- add the ppa from a previous release (such as 16.04) (a lot of cases this will not work due to changes in system libraries)

**Comment by asottile** [comment]
Thanks for the issue!
